# Generated by Django 4.1 on 2022-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerenciador", "0002_remove_users_expiry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resources",
            name="description",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
