# Generated by Django 4.1 on 2022-08-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gerenciador", "0003_alter_resources_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcescheduling",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
